version: "3.8"

services:

  performance-test:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "sleep infinity"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
    restart: unless-stopped

volumes:
  node_modules: